import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import "./globals.css";
import Categories from "@/components/Categories";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased container mx-auto">
        <Navbar />
        <Categories />
        {children}
      </body>
    </html>
  );
}
